#!/usr/bin/env bats
# Tests for exec-devcontainer.sh overlay generation logic.
# These test the file generation only, NOT actual container operations.

load test_helper

REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/.." && pwd)"

setup() {
  TEST_TMP="$(mktemp -d)"
  mkdir -p "$TEST_TMP/project/.devcontainer"

  # Create minimal devsetup.conf
  cat > "$TEST_TMP/project/.devcontainer/devsetup.conf" <<'EOF'
PROJECT_NAME=testproj
WORKSPACE_MOUNT=project
CONTAINER_SCOPE=per-worktree
BASE_IMAGE=mcr.microsoft.com/devcontainers/base:noble
TIMEZONE=Europe/Berlin
DOCKER_MODE=none
EOF

  # Create minimal init-worktree.sh stub
  cat > "$TEST_TMP/project/.devcontainer/init-worktree.sh" <<'EOF'
#!/bin/bash
echo "COMPOSE_PROJECT_NAME=devcontainer-testproj" > "$(dirname "$0")/.env"
EOF
  chmod +x "$TEST_TMP/project/.devcontainer/init-worktree.sh"
}

teardown() {
  rm -rf "$TEST_TMP"
}

# Run only the overlay generation part of exec-devcontainer (stop before devcontainer CLI)
run_overlay_generation() {
  local x11="${1:-auto}"
  local agents="${2:-true}"
  local personal_conf="$TEST_TMP/personal.conf"

  cat > "$personal_conf" <<EOF
INSTALL_AGENTS=$agents
SYNC_CLAUDE_CONFIG=false
X11_FORWARDING=$x11
CLAUDE_FLAGS=--test-flag
CODEX_FLAGS=--test-codex-flag
EOF

  # Source exec-devcontainer in a subshell, but exit before container operations
  (
    cd "$TEST_TMP/project"
    DEVSETUP_DIR="$REPO_ROOT"
    PERSONAL_CONF="$personal_conf"

    source "$PERSONAL_CONF"

    : "${INSTALL_AGENTS:=true}"
    : "${SYNC_CLAUDE_CONFIG:=true}"
    : "${X11_FORWARDING:=auto}"
    : "${CLAUDE_FLAGS:=--dangerously-skip-permissions --ide --chrome}"
    : "${CODEX_FLAGS:=--dangerously-bypass-approvals-and-sandbox}"

    source ".devcontainer/devsetup.conf"

    : "${SERVICE_NAME:=dev}"

    OUTDIR=".devcontainer"
    mkdir -p "$OUTDIR/scripts"

    if [ "$INSTALL_AGENTS" = true ]; then
      cp "$DEVSETUP_DIR/scripts/install-agents.sh" "$OUTDIR/scripts/"
      cp "$DEVSETUP_DIR/scripts/update-agents.sh" "$OUTDIR/scripts/"
      chmod +x "$OUTDIR/scripts/"*.sh
    fi

    ENABLE_X11=false
    if [ "$X11_FORWARDING" = "always" ]; then
      ENABLE_X11=true
    elif [ "$X11_FORWARDING" = "auto" ] && [[ "${OSTYPE:-}" == linux-gnu* ]]; then
      ENABLE_X11=true
    fi

    if [ "$ENABLE_X11" = true ]; then
      cat > "$OUTDIR/docker-compose.local.yml" <<LOCALCOMPOSE
# Personal docker-compose overrides (generated by exec-devcontainer, gitignored).
services:
  ${SERVICE_NAME}:
    volumes:
      - type: bind
        source: \${X11_SOCKET_DIR:-/tmp}
        target: /tmp/.X11-unix
      - type: bind
        source: \${XAUTHORITY_PATH:-/dev/null}
        target: ${HOME}/.Xauthority
        read_only: true
    environment:
      - DISPLAY=\${DISPLAY}
      - XAUTHORITY=${HOME}/.Xauthority
      - QT_X11_NO_MITSHM=1
LOCALCOMPOSE
    else
      cat > "$OUTDIR/docker-compose.local.yml" <<'LOCALCOMPOSE'
# Personal docker-compose overrides (generated by exec-devcontainer, gitignored).
services: {}
LOCALCOMPOSE
    fi

    # Generate postCreateCommand.local.sh
    {
      cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail
# Personal postCreateCommand overlay
HEADER

      if [ "$INSTALL_AGENTS" = true ]; then
        cat <<'AGENTS'
# Install coding agents
bash .devcontainer/scripts/install-agents.sh
AGENTS
        cat <<ALIASES
# Aliases
alias claude='command claude ${CLAUDE_FLAGS}'
alias codex='command codex ${CODEX_FLAGS}'
ALIASES
      fi
    } > "$OUTDIR/postCreateCommand.local.sh"
    chmod +x "$OUTDIR/postCreateCommand.local.sh"

    # Generate postStartCommand.local.sh
    {
      cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail
# Personal postStartCommand overlay
HEADER

      if [ "$INSTALL_AGENTS" = true ]; then
        cat <<'UPDATE'
bash .devcontainer/scripts/update-agents.sh &
UPDATE
      fi
    } > "$OUTDIR/postStartCommand.local.sh"
    chmod +x "$OUTDIR/postStartCommand.local.sh"
  )
}

# --- Launcher options ---

@test "exec-devcontainer: --help prints usage with all options" {
  run bash "$REPO_ROOT/exec-devcontainer.sh" --help
  assert_success
  assert_output --partial "Usage: exec-devcontainer"
  assert_output --partial "--rebuild"
  assert_output --partial "--help"
}

@test "exec-devcontainer: -h is an alias for --help" {
  run bash "$REPO_ROOT/exec-devcontainer.sh" -h
  assert_success
  assert_output --partial "Usage: exec-devcontainer"
}

@test "exec-devcontainer: --help works without devsetup.conf" {
  rm "$TEST_TMP/project/.devcontainer/devsetup.conf"
  cd "$TEST_TMP/project"
  run bash "$REPO_ROOT/exec-devcontainer.sh" --help
  assert_success
  assert_output --partial "Usage: exec-devcontainer"
}

@test "exec-devcontainer: unknown option fails with hint" {
  cd "$TEST_TMP/project"
  run bash "$REPO_ROOT/exec-devcontainer.sh" --bogus
  assert_failure
  assert_output --partial "unknown option"
}

# --- Config reading ---

@test "exec-devcontainer: fails without devsetup.conf" {
  rm "$TEST_TMP/project/.devcontainer/devsetup.conf"
  cd "$TEST_TMP/project"
  run bash "$REPO_ROOT/exec-devcontainer.sh"
  assert_failure
  assert_output --partial "devsetup.conf not found"
}

# --- X11 overlay generation ---

@test "exec-devcontainer: X11=never generates empty local compose" {
  run_overlay_generation "never"
  run grep "services: {}" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
}

@test "exec-devcontainer: X11=always generates X11 compose" {
  run_overlay_generation "always"
  run grep "X11-unix" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
  run grep "DISPLAY" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
}

@test "exec-devcontainer: X11=auto on Linux generates X11 compose" {
  if [[ "${OSTYPE:-}" != linux-gnu* ]]; then
    skip "Only runs on Linux"
  fi
  run_overlay_generation "auto"
  run grep "X11-unix" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
}

# --- Agent installation ---

@test "exec-devcontainer: agents=true copies scripts" {
  run_overlay_generation "never" "true"
  [ -f "$TEST_TMP/project/.devcontainer/scripts/install-agents.sh" ]
  [ -f "$TEST_TMP/project/.devcontainer/scripts/update-agents.sh" ]
  [ -x "$TEST_TMP/project/.devcontainer/scripts/install-agents.sh" ]
}

@test "exec-devcontainer: agents=true generates install in postCreate" {
  run_overlay_generation "never" "true"
  run grep "install-agents.sh" "$TEST_TMP/project/.devcontainer/postCreateCommand.local.sh"
  assert_success
}

@test "exec-devcontainer: agents=true generates update in postStart" {
  run_overlay_generation "never" "true"
  run grep "update-agents.sh" "$TEST_TMP/project/.devcontainer/postStartCommand.local.sh"
  assert_success
}

@test "exec-devcontainer: agents=false skips agent scripts" {
  run_overlay_generation "never" "false"
  [ ! -f "$TEST_TMP/project/.devcontainer/scripts/install-agents.sh" ]
}

@test "exec-devcontainer: agents=false skips install in postCreate" {
  run_overlay_generation "never" "false"
  run grep "install-agents" "$TEST_TMP/project/.devcontainer/postCreateCommand.local.sh"
  assert_failure
}

# --- Configurable flags ---

@test "exec-devcontainer: custom claude flags in aliases" {
  run_overlay_generation "never" "true"
  run grep "\-\-test-flag" "$TEST_TMP/project/.devcontainer/postCreateCommand.local.sh"
  assert_success
}

@test "exec-devcontainer: custom codex flags in aliases" {
  run_overlay_generation "never" "true"
  run grep "\-\-test-codex-flag" "$TEST_TMP/project/.devcontainer/postCreateCommand.local.sh"
  assert_success
}

# --- Generated files are executable ---

@test "exec-devcontainer: postCreateCommand.local.sh is executable" {
  run_overlay_generation "never"
  [ -x "$TEST_TMP/project/.devcontainer/postCreateCommand.local.sh" ]
}

@test "exec-devcontainer: postStartCommand.local.sh is executable" {
  run_overlay_generation "never"
  [ -x "$TEST_TMP/project/.devcontainer/postStartCommand.local.sh" ]
}

@test "exec-devcontainer: docker-compose.local.yml exists" {
  run_overlay_generation "never"
  [ -f "$TEST_TMP/project/.devcontainer/docker-compose.local.yml" ]
}

# --- Custom service name ---

@test "exec-devcontainer: custom SERVICE_NAME in local compose" {
  echo 'SERVICE_NAME="aof"' >> "$TEST_TMP/project/.devcontainer/devsetup.conf"
  run_overlay_generation "always"
  run grep "  aof:" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
  # Should NOT contain default "dev:" service
  run grep "  dev:" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_failure
}

@test "exec-devcontainer: default SERVICE_NAME is dev" {
  run_overlay_generation "always"
  run grep "  dev:" "$TEST_TMP/project/.devcontainer/docker-compose.local.yml"
  assert_success
}

# --- --remote-env for X11 in exec-devcontainer.sh ---

@test "exec-devcontainer: REMOTE_ENV_ARGS is built with DISPLAY when X11 enabled" {
  run grep 'REMOTE_ENV_ARGS.*(--remote-env "DISPLAY=' "$REPO_ROOT/exec-devcontainer.sh"
  assert_success
}

@test "exec-devcontainer: REMOTE_ENV_ARGS includes XAUTHORITY when X11 enabled" {
  run grep 'REMOTE_ENV_ARGS.*(--remote-env "XAUTHORITY=' "$REPO_ROOT/exec-devcontainer.sh"
  assert_success
}

@test "exec-devcontainer: REMOTE_ENV_ARGS includes QT_X11_NO_MITSHM when X11 enabled" {
  run grep 'REMOTE_ENV_ARGS.*(--remote-env "QT_X11_NO_MITSHM=' "$REPO_ROOT/exec-devcontainer.sh"
  assert_success
}

@test "exec-devcontainer: devcontainer up passes REMOTE_ENV_ARGS" {
  run grep 'devcontainer up.*REMOTE_ENV_ARGS' "$REPO_ROOT/exec-devcontainer.sh"
  assert_success
}

@test "exec-devcontainer: all devcontainer exec calls pass REMOTE_ENV_ARGS" {
  local total_exec remote_env_exec
  total_exec=$(grep -c 'devcontainer exec --workspace-folder' "$REPO_ROOT/exec-devcontainer.sh")
  remote_env_exec=$(grep -c 'devcontainer exec --workspace-folder.*REMOTE_ENV_ARGS' "$REPO_ROOT/exec-devcontainer.sh")
  [ "$total_exec" -eq "$remote_env_exec" ]
}

@test "exec-devcontainer: no --override-config in devcontainer commands" {
  run grep 'devcontainer.*--override-config' "$REPO_ROOT/exec-devcontainer.sh"
  assert_failure
}
