#!/bin/bash
set -e

# exec-devcontainer – Standalone launcher for devcontainer environments.
# Lives in the devsetup repo, symlinked to ~/.local/bin/exec-devcontainer.
# Reads project config from .devcontainer/devsetup.conf,
# generates personal overlays, starts the container, and exec's into it.

DEVSETUP_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"

# ============================================================
# Parse launcher options (before any project command)
# ============================================================

print_help() {
  cat <<'HELP'
Usage: exec-devcontainer [OPTIONS] [COMMAND...]

Builds (if needed) and starts the devcontainer for the current project, then
opens an interactive shell or runs COMMAND inside it. Reads project config from
.devcontainer/devsetup.conf.

Options:
  -r, --rebuild   Stop and remove the dev container and its locally built image,
                  then rebuild from scratch on start. Service containers and
                  named data volumes are kept. Asks for confirmation first.
  -h, --help      Show this help and exit.

Without a COMMAND an interactive bash shell is opened. Any COMMAND after the
options (and its own arguments) runs inside the container.
HELP
}

DO_REBUILD=false
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) print_help; exit 0 ;;
    -r|--rebuild) DO_REBUILD=true; shift ;;
    --) shift; break ;;
    -*) echo "ERROR: unknown option '$1'" >&2; print_help >&2; exit 1 ;;
    *) break ;;
  esac
done

# ============================================================
# Read project config
# ============================================================

CONF=".devcontainer/devsetup.conf"
if [ ! -f "$CONF" ]; then
  echo "ERROR: $CONF not found." >&2
  echo "Run 'devsetup' first to generate the devcontainer setup." >&2
  exit 1
fi

# shellcheck source=/dev/null
source "$CONF"

# ============================================================
# Read personal config (optional)
# ============================================================

PERSONAL_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/devsetup/personal.conf"
if [ -f "$PERSONAL_CONF" ]; then
  # shellcheck source=/dev/null
  source "$PERSONAL_CONF"
fi

# Per-project local overrides (gitignored)
LOCAL_CONF=".devcontainer/devsetup.local.conf"
if [ -f "$LOCAL_CONF" ]; then
  # shellcheck source=/dev/null
  source "$LOCAL_CONF"
fi

# Defaults
: "${WORKSPACE_MOUNT:=project}"
: "${INSTALL_AGENTS:=true}"
: "${CLAUDE_CONFIG_MODE:=none}"
: "${X11_FORWARDING:=auto}"
: "${CLAUDE_FLAGS:=--dangerously-skip-permissions}"
: "${CODEX_FLAGS:=--dangerously-bypass-approvals-and-sandbox}"
: "${SERVICE_NAME:=dev}"

case "$CLAUDE_CONFIG_MODE" in
  share|none) ;;
  *)
    echo "ERROR: invalid CLAUDE_CONFIG_MODE='$CLAUDE_CONFIG_MODE' (expected 'share' or 'none')." >&2
    exit 1
    ;;
esac

# Confirm a forced rebuild up front, before any container work happens.
if [ "$DO_REBUILD" = true ]; then
  echo "WARNING: --rebuild stops and removes the dev container and its built image."
  echo "         Service containers and named data volumes are kept."
  printf "Proceed with rebuild? [y/N] "
  read -r REBUILD_REPLY || REBUILD_REPLY=""
  case "$REBUILD_REPLY" in
    y|Y|yes|YES) ;;
    *) echo "Rebuild aborted."; exit 0 ;;
  esac
fi

# ============================================================
# 1. Generate personal overlay files
# ============================================================

OUTDIR=".devcontainer"
mkdir -p "$OUTDIR/scripts"

# --- Copy agent scripts from devsetup repo ---
if [ "$INSTALL_AGENTS" = true ]; then
  cp "$DEVSETUP_DIR/scripts/install-agents.sh" "$OUTDIR/scripts/"
  cp "$DEVSETUP_DIR/scripts/update-agents.sh" "$OUTDIR/scripts/"
  chmod +x "$OUTDIR/scripts/"*.sh
fi

# --- Determine X11 mode ---
ENABLE_X11=false
if [ "$X11_FORWARDING" = "always" ]; then
  ENABLE_X11=true
elif [ "$X11_FORWARDING" = "auto" ] && [[ "${OSTYPE:-}" == linux-gnu* ]]; then
  ENABLE_X11=true
fi

# --- docker-compose.local.yml ---
# Claude config: full read-write bind-mount when sharing is enabled
CLAUDE_MOUNTS=""
if [ "$CLAUDE_CONFIG_MODE" = "share" ]; then
  if [ -d "$HOME/.claude" ]; then
    CLAUDE_MOUNTS="${CLAUDE_MOUNTS}      - type: bind
        source: ${HOME}/.claude
        target: ${HOME}/.claude
"
  fi
  if [ -f "$HOME/.claude.json" ]; then
    CLAUDE_MOUNTS="${CLAUDE_MOUNTS}      - type: bind
        source: ${HOME}/.claude.json
        target: ${HOME}/.claude.json
"
  fi
fi

if [ "$ENABLE_X11" = true ]; then
  cat > "$OUTDIR/docker-compose.local.yml" <<LOCALCOMPOSE
# Personal docker-compose overrides (generated by exec-devcontainer, gitignored).
services:
  ${SERVICE_NAME}:
    volumes:
      - type: bind
        source: \${X11_SOCKET_DIR:-/tmp}
        target: /X11-unix
      - type: bind
        source: \${XAUTHORITY_PATH:-/dev/null}
        target: ${HOME}/.Xauthority
        read_only: true
${CLAUDE_MOUNTS}    environment:
      - DISPLAY=\${DISPLAY}
      - XAUTHORITY=${HOME}/.Xauthority
      - QT_X11_NO_MITSHM=1
LOCALCOMPOSE
elif [ -n "$CLAUDE_MOUNTS" ]; then
  cat > "$OUTDIR/docker-compose.local.yml" <<LOCALCOMPOSE
# Personal docker-compose overrides (generated by exec-devcontainer, gitignored).
services:
  ${SERVICE_NAME}:
    volumes:
${CLAUDE_MOUNTS}LOCALCOMPOSE
else
  cat > "$OUTDIR/docker-compose.local.yml" <<'LOCALCOMPOSE'
# Personal docker-compose overrides (generated by exec-devcontainer, gitignored).
services: {}
LOCALCOMPOSE
fi

# --- Build --remote-env args for devcontainer CLI ---
# devcontainer exec does not inherit docker-compose environment vars,
# so we pass X11 vars explicitly via --remote-env.
REMOTE_ENV_ARGS=()
if [ "$ENABLE_X11" = true ]; then
  REMOTE_ENV_ARGS+=(--remote-env "DISPLAY=${DISPLAY:-}")
  REMOTE_ENV_ARGS+=(--remote-env "XAUTHORITY=${HOME}/.Xauthority")
  REMOTE_ENV_ARGS+=(--remote-env "QT_X11_NO_MITSHM=1")
fi

# Propagate NuGet feed credentials from host.
if [ -n "${NuGetPackageSourceCredentials_median:-}" ]; then
  REMOTE_ENV_ARGS+=(--remote-env "NuGetPackageSourceCredentials_median=${NuGetPackageSourceCredentials_median}")
fi
if [ -n "${NuGetPackageSourceCredentials_mestus:-}" ]; then
  REMOTE_ENV_ARGS+=(--remote-env "NuGetPackageSourceCredentials_mestus=${NuGetPackageSourceCredentials_mestus}")
fi

# --- postCreateCommand.local.sh ---
{
  cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Personal postCreateCommand overlay (generated by exec-devcontainer, gitignored).

if [ -f /etc/profile ]; then
  # shellcheck disable=SC1091
  . /etc/profile || true
fi
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"
export PATH="$HOME/.local/bin:$PATH"

maybe_add_nvm_node_to_path() {
  local base bin_dir
  for base in "${NVM_DIR:-}" "/usr/local/share/nvm" "$HOME/.nvm"; do
    [ -n "$base" ] || continue
    bin_dir="$(ls -1d "$base/versions/node"/*/bin 2>/dev/null | sort -V | tail -n 1 || true)"
    if [ -n "$bin_dir" ] && [ -x "$bin_dir/node" ]; then
      export PATH="$bin_dir:$PATH"
      return 0
    fi
  done
  return 1
}

maybe_add_nvm_node_to_path || true
HEADER

  if [ "$INSTALL_AGENTS" = true ]; then
    cat <<'AGENTS'

# Verify critical tools
command -v curl >/dev/null 2>&1 || { echo "ERROR: curl not found" >&2; exit 1; }
command -v node >/dev/null 2>&1 || { echo "ERROR: node not found" >&2; exit 1; }
command -v npm  >/dev/null 2>&1 || { echo "ERROR: npm not found" >&2; exit 1; }

# Install coding agents
bash .devcontainer/scripts/install-agents.sh
AGENTS

    # Generate aliases block with configurable flags
    cat <<ALIASES

# Setup aliases for coding agents
ALIASES_FILE="\$HOME/.devcontainer_aliases"
cat >"\$ALIASES_FILE" <<'ALIASEOF'
export PATH="\$HOME/.local/bin:\$PATH"
alias claude='command claude ${CLAUDE_FLAGS}'
alias codex='command codex ${CODEX_FLAGS}'
ALIASEOF

SOURCE_LINE='[ -f "\$HOME/.devcontainer_aliases" ] && . "\$HOME/.devcontainer_aliases"'
for rc_file in "\$HOME/.bashrc" "\$HOME/.zshrc"; do
  if [ -f "\$rc_file" ]; then
    grep -qxF "\$SOURCE_LINE" "\$rc_file" || printf '\n%s\n' "\$SOURCE_LINE" >>"\$rc_file"
  else
    printf '%s\n' "\$SOURCE_LINE" >"\$rc_file"
  fi
done

# Ensure ~/.local/bin is on PATH for bash
BASH_PATH_LINE='export PATH="\$HOME/.local/bin:\$PATH"'
if [ -f "\$HOME/.bashrc" ]; then
  grep -qxF "\$BASH_PATH_LINE" "\$HOME/.bashrc" || printf '\n%s\n' "\$BASH_PATH_LINE" >>"\$HOME/.bashrc"
fi
ALIASES
  fi
} > "$OUTDIR/postCreateCommand.local.sh"
chmod +x "$OUTDIR/postCreateCommand.local.sh"

# --- postStartCommand.local.sh ---
{
  cat <<'HEADER'
#!/usr/bin/env bash
set -euo pipefail

# Personal postStartCommand overlay (generated by exec-devcontainer, gitignored).

if [ -f /etc/profile ]; then
  # shellcheck disable=SC1091
  . /etc/profile || true
fi
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"
export PATH="$HOME/.local/bin:$PATH"
HEADER

  if [ "$INSTALL_AGENTS" = true ]; then
    cat <<'UPDATE'

# Update coding agents in background
bash .devcontainer/scripts/update-agents.sh &
UPDATE
  fi
} > "$OUTDIR/postStartCommand.local.sh"
chmod +x "$OUTDIR/postStartCommand.local.sh"

# ============================================================
# 2. Install devcontainer CLI if missing
# ============================================================

if ! command -v devcontainer &> /dev/null; then
  echo "Installing @devcontainers/cli..."
  npm install -g @devcontainers/cli
else
  echo "@devcontainers/cli already installed, skipping..."
fi

# ============================================================
# 3. Initialize worktree (unique compose project name)
# ============================================================

echo "Initializing worktree configuration..."
bash .devcontainer/init-worktree.sh

# ============================================================
# 4. Setup X11 forwarding
# ============================================================

if [ "$ENABLE_X11" = true ]; then
  if [[ "${OSTYPE:-}" == linux-gnu* ]]; then
    echo "Configuring X11 for Linux..."

    MISSING_HOST_TOOLS=()
    command -v socat &> /dev/null || MISSING_HOST_TOOLS+=("socat")
    command -v xhost &> /dev/null || MISSING_HOST_TOOLS+=("x11-xserver-utils")

    if [ ${#MISSING_HOST_TOOLS[@]} -gt 0 ]; then
      echo "Installing required host tools: ${MISSING_HOST_TOOLS[*]}..."
      sudo apt-get update -qq && sudo apt-get install -y -qq "${MISSING_HOST_TOOLS[@]}"
    fi

    xhost +local:root 2>/dev/null || true
    export X11_SOCKET_DIR="/tmp/.X11-unix"
    export XAUTHORITY_PATH="${XAUTHORITY:-$HOME/.Xauthority}"
    echo "Using XAUTHORITY at: $XAUTHORITY_PATH"
  else
    echo "Non-Linux OS with X11 forced. Creating dummy X11 paths..."
    mkdir -p .devcontainer/.x11-dummy/socket
    touch .devcontainer/.x11-dummy/xauthority
    export X11_SOCKET_DIR="$(pwd)/.devcontainer/.x11-dummy/socket"
    export XAUTHORITY_PATH="$(pwd)/.devcontainer/.x11-dummy/xauthority"
  fi

  # Write X11 paths to .env so docker-compose.local.yml can reference them
  ENV_FILE=".devcontainer/.env"
  if [ -f "$ENV_FILE" ]; then
    sed -i '/^X11_SOCKET_DIR=/d; /^XAUTHORITY_PATH=/d; /^DISPLAY=/d' "$ENV_FILE"
  fi
  cat >> "$ENV_FILE" <<EOF
X11_SOCKET_DIR=${X11_SOCKET_DIR}
XAUTHORITY_PATH=${XAUTHORITY_PATH}
DISPLAY=${DISPLAY:-}
EOF
fi

# ============================================================
# Force rebuild: tear down existing dev container and image
# ============================================================
# Runs after init-worktree has (re)written .env, so COMPOSE_PROJECT_NAME
# matches the existing container. The teardown keeps service containers and
# named data volumes; the following 'devcontainer up' rebuilds the dev image.

if [ "$DO_REBUILD" = true ]; then
  REBUILD_CPN="$(grep -E '^COMPOSE_PROJECT_NAME=' .devcontainer/.env 2>/dev/null | head -n1 | cut -d= -f2-)"
  # shellcheck source=/dev/null
  source "$DEVSETUP_DIR/lib/rebuild.sh"
  echo "Removing dev container and image for '${REBUILD_CPN:-<none>}'..."
  remove_dev_container_and_image "$REBUILD_CPN" "$SERVICE_NAME"
fi

# ============================================================
# 5. Build & start devcontainer
# ============================================================

echo "Ensuring devcontainer is up-to-date and running..."
DEVCONTAINER_LOG=$(mktemp)
set +e
devcontainer up --workspace-folder . "${REMOTE_ENV_ARGS[@]}" 2>&1 | tee "$DEVCONTAINER_LOG"
DEVCONTAINER_EXIT=${PIPESTATUS[0]}
set -e
DEVCONTAINER_RESULT=$(cat "$DEVCONTAINER_LOG")
rm -f "$DEVCONTAINER_LOG"

CONTAINER_ID=$(echo "$DEVCONTAINER_RESULT" | grep -o '"containerId":"[^"]*"' | cut -d'"' -f4)

if [ -z "$CONTAINER_ID" ] && [ $DEVCONTAINER_EXIT -ne 0 ]; then
  echo "ERROR: devcontainer up failed and no container ID found."
  exit 1
fi

if [ $DEVCONTAINER_EXIT -ne 0 ]; then
  echo "WARNING: devcontainer up reported an error (e.g. postCreateCommand failed), but container is running."
fi

# Wait for devcontainer exec readiness
echo "Waiting for devcontainer to be ready for exec..."
MAX_RETRIES=3
RETRY_COUNT=0
RETRY_DELAY=1
USE_DOCKER_EXEC=false

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
  set +e
  devcontainer exec --workspace-folder . "${REMOTE_ENV_ARGS[@]}" true 2>/dev/null
  EXEC_RESULT=$?
  set -e

  if [ $EXEC_RESULT -eq 0 ]; then
    echo "Devcontainer CLI is ready!"
    break
  fi

  RETRY_COUNT=$((RETRY_COUNT + 1))
  if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
    echo "Container not ready yet, waiting ${RETRY_DELAY}s... (attempt $RETRY_COUNT/$MAX_RETRIES)"
    sleep $RETRY_DELAY
  else
    set +e
    HAS_INTELLIJ_LABEL=$(docker inspect "$CONTAINER_ID" 2>/dev/null | grep -c "com.intellij.devcontainer")
    set -e

    if [ "$HAS_INTELLIJ_LABEL" -gt 0 ]; then
      echo "Detected container started by IntelliJ. Using docker exec as fallback."
    else
      echo "WARNING: devcontainer exec not available. Using docker exec as fallback."
    fi
    USE_DOCKER_EXEC=true
  fi
done

# ============================================================
# 6. Sync host configs into container
# ============================================================

exec_in_container() {
  if [ "$USE_DOCKER_EXEC" = true ]; then
    docker exec -i "$CONTAINER_ID" "$@"
  else
    devcontainer exec --workspace-folder . "${REMOTE_ENV_ARGS[@]}" "$@"
  fi
}

copy_to_container() {
  local src="$1" dest="$2"
  if [ "$USE_DOCKER_EXEC" = true ]; then
    cat "$src" | docker exec -i "$CONTAINER_ID" bash -c "cat > $dest"
  else
    cat "$src" | devcontainer exec --workspace-folder . "${REMOTE_ENV_ARGS[@]}" bash -c "cat > $dest"
  fi
}

# --- Symlink X11 socket into /tmp (docker-in-docker mounts tmpfs on /tmp) ---
if [ "$ENABLE_X11" = true ]; then
  if [ "$USE_DOCKER_EXEC" = true ]; then
    docker exec -u root "$CONTAINER_ID" ln -sfn /X11-unix /tmp/.X11-unix || true
  else
    devcontainer exec --workspace-folder . "${REMOTE_ENV_ARGS[@]}" sudo ln -sfn /X11-unix /tmp/.X11-unix || true
  fi
fi

# ============================================================
# 7. Exec into container
# ============================================================

# Determine container workspace path
if [ "$WORKSPACE_MOUNT" = "parent" ]; then
  CONTAINER_WORKDIR="/workspaces/$(basename "$(pwd)")"
else
  CONTAINER_WORKDIR="/workspaces/${PROJECT_NAME}"
fi

if [ $# -eq 0 ]; then
  set -- bash
fi

if [ "$USE_DOCKER_EXEC" = true ]; then
  DOCKER_ENV_ARGS=()

  # Propagate NuGet feed credentials from host.
  if [ -n "${NuGetPackageSourceCredentials_median:-}" ]; then
    DOCKER_ENV_ARGS+=(-e "NuGetPackageSourceCredentials_median=${NuGetPackageSourceCredentials_median}")
  fi
  if [ -n "${NuGetPackageSourceCredentials_mestus:-}" ]; then
    DOCKER_ENV_ARGS+=(-e "NuGetPackageSourceCredentials_mestus=${NuGetPackageSourceCredentials_mestus}")
  fi

  if [ "$ENABLE_X11" = true ]; then
    # Check if X11 Unix socket is mounted in container
    X11_SOCKET_MOUNTED=$(docker exec "$CONTAINER_ID" test -d /tmp/.X11-unix && echo "yes" || echo "no")

    if [ "$X11_SOCKET_MOUNTED" = "yes" ] && [ -n "${DISPLAY:-}" ]; then
      DOCKER_ENV_ARGS+=(-e "DISPLAY=$DISPLAY")
      [ -n "${XAUTHORITY_PATH:-}" ] && DOCKER_ENV_ARGS+=(-e "XAUTHORITY=${HOME}/.Xauthority")
    else
      # No Unix socket – use TCP via host IP
      echo "X11 Unix socket not mounted. Setting up TCP forwarding via socat..."

      xhost +local:docker 2>/dev/null || true
      xhost +SI:localuser:root 2>/dev/null || true
      xhost + 2>/dev/null || true

      DISPLAY_NUM="${DISPLAY#:}"
      DISPLAY_NUM="${DISPLAY_NUM%%.*}"
      : "${DISPLAY_NUM:=0}"

      X11_TCP_PORT=$((6010 + DISPLAY_NUM))
      X11_UNIX_SOCKET="/tmp/.X11-unix/X${DISPLAY_NUM}"

      if ! pgrep -f "socat.*TCP-LISTEN:${X11_TCP_PORT}" > /dev/null 2>&1; then
        if [ -S "$X11_UNIX_SOCKET" ]; then
          ACTUAL_X11_SOCKET="$X11_UNIX_SOCKET"
        elif [ -S "/tmp/.X11-unix/X0" ]; then
          ACTUAL_X11_SOCKET="/tmp/.X11-unix/X0"
          echo "Using fallback X11 socket: $ACTUAL_X11_SOCKET"
        else
          ACTUAL_X11_SOCKET=""
        fi

        if [ -n "$ACTUAL_X11_SOCKET" ]; then
          echo "Starting X11 TCP forward on port ${X11_TCP_PORT} -> ${ACTUAL_X11_SOCKET}..."
          socat TCP-LISTEN:${X11_TCP_PORT},fork,reuseaddr,bind=0.0.0.0 UNIX-CONNECT:${ACTUAL_X11_SOCKET} &
          SOCAT_PID=$!
          sleep 0.5

          if kill -0 $SOCAT_PID 2>/dev/null; then
            echo "X11 TCP forward started successfully (PID: $SOCAT_PID)"
          else
            echo "WARNING: socat failed to start X11 TCP forward."
          fi
        else
          echo "WARNING: No X11 Unix socket found"
        fi
      else
        echo "X11 TCP forward already running on port ${X11_TCP_PORT}"
      fi

      HOST_IP=$(docker network inspect bridge --format '{{range .IPAM.Config}}{{.Gateway}}{{end}}' 2>/dev/null || echo "172.17.0.1")

      if docker exec "$CONTAINER_ID" getent hosts host.docker.internal > /dev/null 2>&1; then
        X11_HOST="host.docker.internal"
      else
        X11_HOST="$HOST_IP"
        echo "host.docker.internal not available, using IP: $HOST_IP"
      fi

      DOCKER_ENV_ARGS+=(-e "DISPLAY=${X11_HOST}:$((10 + DISPLAY_NUM))")
    fi

    # Ensure X11 tools in container
    echo "Ensuring X11 tools are installed in container..."
    docker exec -u root "$CONTAINER_ID" bash -c '
      MISSING_PKGS=()
      command -v xclip &> /dev/null || MISSING_PKGS+=("xclip")
      command -v xsel &> /dev/null || MISSING_PKGS+=("xsel")
      command -v xauth &> /dev/null || MISSING_PKGS+=("xauth")
      command -v nc &> /dev/null || MISSING_PKGS+=("netcat-openbsd")

      if [ ${#MISSING_PKGS[@]} -gt 0 ]; then
        echo "Installing in container: ${MISSING_PKGS[*]}..."
        apt-get update -qq && apt-get install -y -qq "${MISSING_PKGS[@]}" 2>/dev/null
      fi
    ' || true
  fi


  if [ -t 0 ]; then
    exec docker exec -it "${DOCKER_ENV_ARGS[@]}" -u "$(id -un)" -w "$CONTAINER_WORKDIR" "$CONTAINER_ID" "$@"
  else
    exec docker exec -i "${DOCKER_ENV_ARGS[@]}" -u "$(id -un)" -w "$CONTAINER_WORKDIR" "$CONTAINER_ID" "$@"
  fi
else
  exec devcontainer exec --workspace-folder . "${REMOTE_ENV_ARGS[@]}" "$@"
fi
